version: "3.7"

services:
  app:
    image: httpd:2.4
    ports:
      - 8008:80
    volumes:
      - ./public:/usr/local/apache2/htdocs
  hugo:
    image: klakegg/hugo
    command: server
    volumes:
      - ".:/src"
    ports:
      - 1313:1313
